const STORE_KEY='mir_iymana_ready_products_v1'; const CART_KEY='mir_iymana_ready_cart_v1'; const FAV_KEY='mir_iymana_ready_fav_v1'; const defaultProducts=[{"id": 1, "name": "Nafis abaya", "cat": "kiyimlar", "price": 450000, "old": 0, "size": "S / M / L", "color": "Qora", "badge": "NEW", "img": "p1.jpg"}, {"id": 2, "name": "Premium to‘plam", "cat": "kiyimlar", "price": 680000, "old": 850000, "size": "S / M / L / XL", "color": "Bej", "badge": "NEW", "img": "p2.jpg"}, {"id": 3, "name": "Qishki set", "cat": "new", "price": 550000, "old": 0, "size": "S / M / L", "color": "Kulrang", "badge": "NEW", "img": "p3.jpg"}, {"id": 4, "name": "Koktel ko‘ylak", "cat": "discount", "price": 420000, "old": 480000, "size": "S / M / L", "color": "Qizil", "badge": "SALE", "img": "p4.jpg"}, {"id": 5, "name": "Sportiv kostyum", "cat": "kiyimlar", "price": 480000, "old": 0, "size": "S / M / L", "color": "Ko‘k", "badge": "NEW", "img": "p5.jpg"}, {"id": 6, "name": "Khaki street set", "cat": "kiyimlar", "price": 390000, "old": 0, "size": "M / L / XL", "color": "Khaki", "badge": "", "img": "p6.jpg"}, {"id": 7, "name": "Winter set", "cat": "new", "price": 590000, "old": 0, "size": "S / M / L", "color": "Oq-kulrang", "badge": "NEW", "img": "p7.jpg"}, {"id": 8, "name": "Moviy premium ko‘ylak", "cat": "new", "price": 620000, "old": 0, "size": "S / M / L", "color": "Moviy", "badge": "NEW", "img": "p8.jpg"}, {"id": 9, "name": "Dubai Abaya", "cat": "kiyimlar", "price": 450000, "old": 0, "size": "S / M / L / XL", "color": "Qora", "badge": "", "img": "p9.jpg"}, {"id": 10, "name": "Loafer oyoq kiyim", "cat": "aksessuarlar", "price": 220000, "old": 0, "size": "36-41", "color": "Har xil", "badge": "", "img": "p10.jpg"}, {"id": 11, "name": "Pushti klassik ko‘ylak", "cat": "discount", "price": 520000, "old": 600000, "size": "S / M / L", "color": "Pushti", "badge": "SALE", "img": "p11.jpg"}, {"id": 12, "name": "Bordo nafis ko‘ylak", "cat": "discount", "price": 490000, "old": 0, "size": "S / M / L / XL", "color": "Bordo", "badge": "", "img": "p12.jpg"}];
const ADMIN_LOGIN="admin"; const ADMIN_PASSWORD="12345";
function getProducts(){return JSON.parse(localStorage.getItem(STORE_KEY)||JSON.stringify(defaultProducts))}
function saveProducts(p){localStorage.setItem(STORE_KEY,JSON.stringify(p))}
function money(n){return Number(n).toLocaleString("uz-UZ")+" so‘m"}
function getCart(){return JSON.parse(localStorage.getItem(CART_KEY)||"[]")}
function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));count()}
function getFav(){return JSON.parse(localStorage.getItem(FAV_KEY)||"[]")}
function saveFav(f){localStorage.setItem(FAV_KEY,JSON.stringify(f));count()}
function count(){document.querySelectorAll("#cartCount").forEach(x=>x.textContent=getCart().length);document.querySelectorAll("#favCount").forEach(x=>x.textContent=getFav().length)}
function toast(t){let el=document.querySelector("#toast"); if(!el){el=document.createElement("div");el.id="toast";el.className="toast";document.body.appendChild(el)} el.textContent=t;el.style.display="block";setTimeout(()=>el.style.display="none",1800)}
function toggleFav(id){let f=getFav();if(f.includes(id)){f=f.filter(x=>x!==id);toast("Sevimlidan olib tashlandi")}else{f.push(id);toast("Sevimliga qo‘shildi ❤️")}saveFav(f);renderProducts(document.body.dataset.filter||"all")}
function card(p){let fav=getFav().includes(p.id);return `<div class="product">${p.badge?`<div class="badge">${p.badge}</div>`:""}<button class="fav-btn ${fav?"active":""}" onclick="toggleFav(${p.id})">♥</button><img src="images/${p.img}" onerror="this.src='images/logo.jpg'"><div class="pbody"><h3>${p.name}</h3><div><span class="price">${money(p.price)}</span>${p.old?`<span class="old">${money(p.old)}</span>`:""}</div><div class="colors"><span style="background:#111"></span><span style="background:#c01665"></span><span style="background:#b59b61"></span><span style="background:#777"></span></div><div class="sizes">${String(p.size).split("/").map(s=>`<span>${s.trim()}</span>`).join("")}</div><div class="actions"><button class="btn small" onclick="addToCart(${p.id})">🛒 Savatga qo‘shish</button><button class="btn black small" onclick="tg('${p.name}')">✈ Telegram orqali buyurtma</button></div></div></div>`}
function renderProducts(filter="all"){let box=document.querySelector("#products");if(!box)return;let d=getProducts();let q=(document.querySelector("#search")?.value||"").toLowerCase();let sort=document.querySelector("#sort")?.value||"";if(filter=="favorites")d=d.filter(p=>getFav().includes(p.id));else if(filter!="all")d=d.filter(p=>p.cat==filter);if(q)d=d.filter(p=>p.name.toLowerCase().includes(q)||p.color.toLowerCase().includes(q));if(sort=="cheap")d.sort((a,b)=>a.price-b.price);if(sort=="expensive")d.sort((a,b)=>b.price-a.price);box.innerHTML=d.length?d.map(card).join(""):"<p>Mahsulot topilmadi</p>"}
function addToCart(id){let p=getProducts().find(x=>x.id==id);let c=getCart();c.push(p);saveCart(c);toast("Savatga qo‘shildi 🛒")}
function tg(name){window.open("https://t.me/marufovv?text="+encodeURIComponent("Assalomu alaykum, buyurtma qilmoqchiman: "+name),"_blank")}
function renderCart(){let b=document.querySelector("#cartBody");if(!b)return;let c=getCart();b.innerHTML=c.map((p,i)=>`<tr><td><img src="images/${p.img}"> ${p.name}</td><td>${money(p.price)}</td><td>${p.size}</td><td><button class="btn black small" onclick="removeCart(${i})">O‘chirish</button></td></tr>`).join("");document.querySelector("#total").textContent=money(c.reduce((s,p)=>s+Number(p.price),0))}
function removeCart(i){let c=getCart();c.splice(i,1);saveCart(c);renderCart()}
function submitOrder(){let c=getCart();if(!c.length){toast("Savat bo‘sh");return}let list=c.map(p=>`${p.name} - ${money(p.price)}`).join("\n");let total=money(c.reduce((s,p)=>s+Number(p.price),0));window.open("https://t.me/marufovv?text="+encodeURIComponent("Yangi buyurtma:\n"+list+"\nUmumiy summa: "+total),"_blank")}
function openSearch(){document.querySelector("#searchOverlay").style.display="flex";document.querySelector("#globalSearch").focus();globalSearch()}
function closeSearch(){document.querySelector("#searchOverlay").style.display="none"}
function globalSearch(){let q=(document.querySelector("#globalSearch")?.value||"").toLowerCase();let d=getProducts().filter(p=>p.name.toLowerCase().includes(q)||p.color.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q));document.querySelector("#searchResults").innerHTML=d.map(p=>`<div class="search-item"><img src="images/${p.img}" onerror="this.src='images/logo.jpg'"><div><b>${p.name}</b><br><span class="price">${money(p.price)}</span><br><button class="btn small" onclick="addToCart(${p.id})">Savatga</button></div></div>`).join("") || "<p>Topilmadi</p>"}
function adminLogin(e){e.preventDefault();let l=document.querySelector("#adminUser").value.trim();let p=document.querySelector("#password").value.trim();let a=document.querySelector("#loginAlert");if(l===ADMIN_LOGIN&&p===ADMIN_PASSWORD){sessionStorage.setItem("mir_admin","yes");window.location.href="admin-panel.html"}else{a.style.display="block";a.textContent="Login yoki parol noto‘g‘ri!"}}
function guard(){if(document.body.dataset.admin==="panel"&&sessionStorage.getItem("mir_admin")!=="yes")location.href="admin.html"}
function logout(){sessionStorage.removeItem("mir_admin");location.href="admin.html"}
function renderAdmin(){let b=document.querySelector("#adminProducts");if(!b)return;b.innerHTML=getProducts().map(p=>`<tr><td><img src="images/${p.img}" onerror="this.src='images/logo.jpg'"></td><td>${p.name}</td><td>${money(p.price)}</td><td>${p.cat}</td><td><button class="btn black small" onclick="editPrice(${p.id})">Narx</button> <button class="btn black small" onclick="del(${p.id})">O‘chirish</button></td></tr>`).join("")}
function addProduct(e){e.preventDefault();let f=new FormData(e.target), p=getProducts();p.push({id:Date.now(),name:f.get("name"),cat:f.get("cat"),price:+f.get("price"),old:+(f.get("old")||0),size:f.get("size"),color:f.get("color"),badge:f.get("badge"),img:f.get("img")});saveProducts(p);e.target.reset();renderAdmin();toast("Mahsulot qo‘shildi")}
function editPrice(id){let p=getProducts(), it=p.find(x=>x.id==id), n=prompt("Yangi narx:",it.price);if(n){it.price=+n;saveProducts(p);renderAdmin()}}
function del(id){if(confirm("O‘chirilsinmi?")){saveProducts(getProducts().filter(x=>x.id!=id));renderAdmin()}}
function buildSearchOverlay(){if(document.querySelector("#searchOverlay"))return;let o=document.createElement("div");o.id="searchOverlay";o.className="search-overlay";o.innerHTML=`<div class="search-box"><div class="search-row"><input id="globalSearch" placeholder="Mahsulot qidirish..." oninput="globalSearch()"><button class="btn black" onclick="closeSearch()">Yopish</button></div><div id="searchResults" class="search-results"></div></div>`;document.body.appendChild(o)}
document.addEventListener("DOMContentLoaded",()=>{buildSearchOverlay();guard();count();renderProducts(document.body.dataset.filter||"all");renderCart();renderAdmin();document.querySelector("#search")?.addEventListener("input",()=>renderProducts(document.body.dataset.filter||"all"));document.querySelector("#sort")?.addEventListener("change",()=>renderProducts(document.body.dataset.filter||"all"));});
